### ISSUE TITLE
Missing Directories and File

### ISSUE THREAD

**Issue by jessengolab** [jessengolab/ide-data-science-template#3]
ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/data/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/data/Backups/workspaces.json'\n    at Timeout.setTimeout [as _onTimeout] (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:52540:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}

**Comment by KaneRodriguez** [comment]
Looks this will be fixed in the next release of code-server, and you can just ignore it for now.

https://github.com/cdr/code-server/issues/121#issuecomment-480935676

**Comment by jessengolab** [comment]
Thanks @KaneRodriguez will close this and wait for the next release
cdr/code-server#121 (comment)
